import Stripe from "stripe";

// Mid-January 2025 — deterministic date that renders as "Jan 2025" in any timezone.
const DEFAULT_PERIOD_END = 1737504000;

interface MockSubscriptionOptions {
  unitAmount?: number;
  periodEnd?: number;
}

export function createMockSubscription(
  options: MockSubscriptionOptions = {},
): Stripe.Subscription {
  const { unitAmount = 10000, periodEnd = DEFAULT_PERIOD_END } = options;

  return {
    id: "sub_123",
    object: "subscription",
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
      liability: null,
      disabled_reason: null,
    },
    billing_cycle_anchor: 1234567890,
    billing_cycle_anchor_config: null,
    billing_mode: {
      type: "classic",
      flexible: null,
    },
    billing_thresholds: null,
    billing_schedules: [],
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: null,
    collection_method: "charge_automatically",
    created: 1234567890,
    currency: "usd",
    customer: "cus_123",
    customer_account: "ca_123",
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    description: null,
    discounts: [],
    ended_at: null,
    invoice_settings: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: { type: "self" },
    },
    items: {
      object: "list",
      data: [
        {
          id: "si_123",
          object: "subscription_item",
          billing_thresholds: null,
          created: 1234567890,
          discounts: [],
          metadata: {},
          plan: {
            id: "plan_123",
            object: "plan",
            active: true,
            amount: unitAmount,
            amount_decimal: Stripe.Decimal.from(unitAmount),
            billing_scheme: "per_unit",
            created: 1234567890,
            currency: "usd",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_123",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_123",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1234567890,
            currency: "usd",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_123",
            recurring: {
              interval: "month",
              interval_count: 1,
              usage_type: "licensed",
              meter: null,
              trial_period_days: null,
            },
            tax_behavior: null,
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: unitAmount,
            unit_amount_decimal: Stripe.Decimal.from(unitAmount),
          },
          quantity: 1,
          subscription: "sub_123",
          tax_rates: [],
          current_period_end: periodEnd,
          current_period_start: periodEnd - 30 * 24 * 60 * 60,
        },
      ],
      has_more: false,
      url: "/v1/subscription_items",
    },
    latest_invoice: null,
    livemode: false,
    managed_payments: null,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: null,
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    schedule: null,
    start_date: 1234567890,
    status: "active",
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: null,
    trial_start: null,
  };
}
